[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'mv package.json package.json.vercel',
  'cd server && npm install',
  'cd server && npx prisma generate',
  'mv package.json.vercel package.json'
]

[phases.build]
cmds = ['echo "Backend build complete"']

[start]
cmd = 'cd server && node index.js'
