[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm ci && npm run prisma:generate"

[deploy]
startCommand = "cd server && npm run start:js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
